### ISSUE TITLE
Different initialization commands for AHT10 and AHT20

### ISSUE THREAD

**Issue by targetblank** [adafruit/Adafruit_CircuitPython_AHTx0#3]
While porting the library to MicroPython I maybe found an issue with initialization commands. Your library uses [0xE1](https://github.com/adafruit/Adafruit_CircuitPython_AHTx0/blob/123d11b19c1e379885f03c1de9797cc8d55999cc/adafruit_ahtx0.py#L54), which is right for the AHT10 according to the [datasheet](https://server4.eca.ir/eshop/AHT10/Aosong_AHT10_en_draft_0c.pdf). The AHT20 expects 0xBE, see [datasheet](https://cdn-learn.adafruit.com/assets/assets/000/091/676/original/AHT20-datasheet-2020-4-16.pdf?1591047915).
I found 0xE1 working well with the AHT10 and didn't have the chance to test with a AHT20, yet. Since Adafruit is also vendor of a AHT20 module, I am sure you have tested your library and maybe there is only some confusion in datasheets or simply both commands are working. Anyway it would be great, if you can have a look at that and share your thoughts with me.

**Comment by jposada202020** [comment]
So first to take a look at this.
As you probably aleady notice, the only bits that matter for both sensor are 7  and 3. 1 is the same for both and will only put a Busy flag, and the we have bit 3 that is the calibration parameter.

However for AHT20. the datasheet mentions
![image](https://user-images.githubusercontent.com/34255413/114084731-83d4e180-987e-11eb-8045-ce672c895144.png)

I tested this changing the parameter as you suggested for a AHT20 with both 0xE1 and 0xBE and it worked for both cases
https://github.com/adafruit/Adafruit_CircuitPython_AHTx0/blob/6ab98fc4626f94d09d9ce9eaa12a9f1337aecfe9/adafruit_ahtx0.py#L37

I tested this in
```python
Adafruit CircuitPython 6.2.0-beta.3-188-g05ed179e1 on 2021-03-15; Adafruit Feather RP2040 with rp2040
```

**Comment by jposada202020** [comment]
@targetblank Let me know if you have any further comments :). I would like to close this issue. Thanks.

**Comment by jposada202020** [comment]
Closing for now. Was tested as previously mentioned without any issue

**Comment by targetblank** [comment]
Thanks @jposada202020 for testing and sharing your results! So in the end it doesn't matter which init command is used in practical terms. Anyway it would be interesting to know, if there is any reason why they are different.
